import { definePlugin } from "@osndot/sdk";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";

export default definePlugin({
    name: "@osndot/plugin-env",
    version: "0.2.0",
    description: "Environment configuration management for OSN",
    setup(ctx) {
        return {
            commands: [
                {
                    name: "env:list",
                    description: "List all environment variables from .env file",
                    handler: async () => {
                        const envFilePath = join(ctx.cwd, ".env");
                        if (!existsSync(envFilePath)) {
                            ctx.logger.warn("No .env file found in this directory.");
                            ctx.logger.info("Run 'osn env init' to create one.");
                            return;
                        }

                        const content = await readFile(envFilePath, "utf-8");
                        const lines = content
                            .split("\n")
                            .filter((line) => line.trim() && !line.startsWith("#"));

                        if (lines.length === 0) {
                            ctx.logger.info("No environment variables defined.");
                            return;
                        }

                        ctx.logger.info("Environment variables:");
                        for (const line of lines) {
                            const [key] = line.split("=");
                            if (key) {
                                ctx.logger.info(`  ${key.trim()} = ****`);
                            }
                        }
                    },
                },
                {
                    name: "env:init",
                    description: "Create a .env file with defaults",
                    handler: async () => {
                        const envFilePath = join(ctx.cwd, ".env");
                        if (existsSync(envFilePath)) {
                            ctx.logger.warn(".env file already exists.");
                            return;
                        }

                        const template = [
                            "# OSN Environment Configuration",
                            "# Generated by @osndot/plugin-env",
                            "",
                            "NODE_ENV=development",
                            "PORT=3000",
                            "",
                        ].join("\n");

                        await writeFile(envFilePath, template, "utf-8");
                        ctx.logger.success(".env file created successfully.");
                    },
                },
            ],
            hooks: {
                onLoad: () => ctx.logger.debug("Env plugin loaded."),
            },
        };
    },
});
